import { Html, Main,Head, NextScript } from "next/document";
// import Head from "next/head";

export default function Document() {
  return (
    <Html lang="en">
      {/* <Head /> */}
      <Head>
        <title>Pokemon-Catalog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
